DormitoryManagement/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dormitory.Entity.Data;
using DormitoryManagement.Helper;
using System.IO;
using Dormitory.Business.Interface;
using Dormitory.Repositories.IServiceRepositories;
using Dormitory.Repositories.Repositories;

namespace DormitoryManagement.Controllers
{
    public class StudentsController : Controller
    {
        private readonly DormitoryContext _context;
        private IDiagramRepository _diagramRepository;
        private IUnitOfWork _unitOfWork;

        public StudentsController(DormitoryContext context, IDiagramRepository diagramRepository, IUnitOfWork unitOfWork)
        {
            _context = context;
            _diagramRepository = diagramRepository;
            _unitOfWork = unitOfWork;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
            var dormitoryContext = _context.Student.Include(s => s.IdroomNavigation);
            return View(await dormitoryContext.ToListAsync());
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student              
                .Include(s => s.IdroomNavigation)
                .FirstOrDefaultAsync(m => m.KeyId == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public  IActionResult Create()
        {
            var student = new Student();                       
            ViewData["Idroom"] = new SelectList(_context.Room, "KeyId", "Name");
            return PartialView("CreatePartialModal", student);
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("KeyId,IdStudent,Name,Gender,DOB,Faculty,Class,PhoneNumber,Address,PhoneParents,AddressOfParents,PolicyArea,Teacher,Idroom,Email,Idcard,Image")] Student student, Microsoft.AspNetCore.Http.IFormFile image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    //Set Key Name
                    string ImageName = Guid.NewGuid().ToString() + Path.GetExtension(image.FileName);

                    //Get url To Save
                    string SavePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/avatar/", ImageName);

                    using (var stream = new FileStream(SavePath, FileMode.Create))
                    {
                        image.CopyTo(stream);
                    }
                    student.Image = ImageName;
                }
                var query = _diagramRepository.FindById(student.Idroom);
                query.Reservation -= 1;
                _unitOfWork.Commit();
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }         
            ViewData["Idroom"] = new SelectList(_context.Room, "KeyId", "Name", student.Idroom);
            return RedirectToAction(nameof(Index));
        }     

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .Include(s => s.IdroomNavigation.IdcategoryNavigation)
                .FirstOrDefaultAsync(x => x.KeyId == id);
            if (student == null)
            {
                return NotFound();
            }
            ViewData["Idroom"] = new SelectList(_context.Room, "KeyId", "Name", student.Idroom);
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("KeyId,IdStudent,Name,Gender,DOB,Faculty,Class,PhoneNumber,Address,PhoneParents,AddressOfParents,PolicyArea,Teacher,Idroom,Email,Idcard,Image")] Student student , Microsoft.AspNetCore.Http.IFormFile image)
        {
            if (id != student.KeyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    if (image != null)
                    {
                        //Set Key Name
                        string ImageName = Guid.NewGuid().ToString() + Path.GetExtension(image.FileName);

                        //Get url To Save
                        string SavePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/avatar/", ImageName);

                        using (var stream = new FileStream(SavePath, FileMode.Create))
                        {
                            image.CopyTo(stream);
                        }
                        student.Image = ImageName;
                    }
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.KeyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Edit");
            }
            ViewData["Idroom"] = new SelectList(_context.Room, "KeyId", "Idroom", student.Idroom);
            return RedirectToAction("Edit");
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .Include(s => s.IdroomNavigation)
                .Include(s=> s.Contract)
                .Include(s=> s.Follow)
                .FirstOrDefaultAsync(m => m.KeyId == id);
            if (student == null)
            {
                return NotFound();
            }

            return new JsonResult(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Student.FindAsync(id);
            _context.Student.Remove(student);
            await _context.SaveChangesAsync();
            return new JsonResult("Done");
        }

        private bool StudentExists(int id)
        {
            return _context.Student.Any(e => e.KeyId == id);
        }
        /*------------------------------------------------------------------------------------------------------*/
        public async Task<IActionResult> LoadDataWithPaging(Helper.DTParameters dtParameters)
        {
            var searchBy = dtParameters.Search?.Value;

            var orderCriteria = string.Empty;
            var orderAscendingDirection = true;

            if (dtParameters.Order != null)
            {
                // in this example we just default sort on the 1st column
                orderCriteria = dtParameters.Columns[dtParameters.Order[0].Column].Data;
                orderAscendingDirection = dtParameters.Order[0].Dir.ToString().ToLower() == "asc";
            }
            else
            {
                // if we have an empty search then just order the results by Id ascending
                orderCriteria = "KeyId";
                orderAscendingDirection = true;
            }

            var result = await _context.Student
                .ToListAsync();

            //var rooms = new List<Room>();
            //try
            //{
            //    foreach (var item in result)
            //    {
            //        var room = _diagramRepository.FindById(item.Idroom);

            //        rooms.Add(room);

            //    }
            //}
            //catch (Exception e)
            //{

            //    throw;
            //}

            var totalResultsCount = result.Count();
            if (!string.IsNullOrEmpty(searchBy))
            {
                result = result.Where(r => r.Name.ToLower().Contains(searchBy.ToLower()) || r.KeyId.Equals(searchBy) || r.IdroomNavigation.Name.Equals(searchBy)).ToList();
            }
            result = orderAscendingDirection ?
                result.AsQueryable().OrderByDynamic(orderCriteria, LinqExtension.Order.Asc).ToList() :
                result.AsQueryable().OrderByDynamic(orderCriteria, LinqExtension.Order.Desc).ToList();

            var filteredResultsCount = result.Count();
            return new JsonResult(new
            {
                draw = dtParameters.Draw,
                recordsTotal = totalResultsCount,
                recordsFiltered = filteredResultsCount,
                data = result.Skip(dtParameters.Start).Take(dtParameters.Length),
                //room = rooms
            });


        }
    }
}

DormitoryManagement/Views/Students/Edit.cshtml
@model Dormitory.Entity.Data.Student

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- partial -->
<div class="content-wrapper">
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb bg-inv">
            <li class="breadcrumb-item"><img src="~/images/Icon/home.png" style="width:20px; height:20px;" /></li>
            <li class="breadcrumb-item" aria-current="page">Student</li>
            <li class="breadcrumb-item active" aria-current="page">Infomation</li>
        </ol>
    </nav>

    <div class="row user-profile">
        <div class="col-lg-4 side-left d-flex align-items-stretch">
            <div class="row">
                <div class="col-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body avatar">
                            <h4 class="card-title">Info</h4>
                            <img src="~/images/avatar/@Html.DisplayFor(model => model.Image)" alt="">
                            <p class="name"> @Html.DisplayFor(model => model.Name)</p>
                            <p class="designation">-  Student -</p>
                            <a class="d-block text-center text-dark">@Html.DisplayFor(model => model.Email)</a>
                            <a class="d-block text-center text-dark">+84  @Html.DisplayFor(model => model.PhoneNumber)</a>
                            <a class="d-block text-center text-dark"> ID Card :@Html.DisplayFor(model => model.Idcard)</a>
                        </div>
                    </div>
                </div>
                <div class="col-12 stretch-card">
                    <div class="card">
                        <div class="card-body overview">
                            <ul class="achivements">
                                <li><p style="font-size:13px">@Html.DisplayFor(model => model.IdroomNavigation.Name)</p><p>Room</p></li>
                               
                            </ul>
                            <div class="wrapper about-user">
                                <h4 class="card-title mt-4 mb-3">About</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam consectetur ex quod.</p>
                            </div>
                            <div class="info-links">
                                <a class="website" href="http://bootstrapdash.com/">
                                    <i class="mdi mdi-earth text-gray"></i>
                                    <span>http://bootstrapdash.com/</span>
                                </a>
                                <a class="social-link" href="#">
                                    <i class="mdi mdi-facebook text-gray"></i>
                                    <span>https://www.facebook.com/johndoe</span>
                                </a>
                                <a class="social-link" href="#">
                                    <i class="mdi mdi-linkedin text-gray"></i>
                                    <span>https://www.linkedin.com/johndoe</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-8 side-right stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="wrapper d-block d-sm-flex align-items-center justify-content-between">
                        <h4 class="card-title mb-0">Details</h4>
                        <ul class="nav nav-tabs tab-solid tab-solid-primary mb-0" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="info-tab" data-toggle="tab" href="#info" role="tab" aria-controls="info" aria-expanded="true">Info</a>
                            </li>                          
                            <li class="nav-item">
                                <a class="nav-link" id="security-tab" data-toggle="tab" href="#security" role="tab" aria-controls="security">Security</a>
                            </li>
                        </ul>
                    </div>
                    <div class="wrapper">
                        <hr>
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="info" role="tabpanel" aria-labelledby="info">
                                <form id="editStudent" method="post" enctype="multipart/form-data">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="form-group">
                                        <input asp-for="KeyId" class="form-control" type="hidden" />
                                        <span asp-validation-for="KeyId" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="Idstudent">ID Student</label>
                                        <input asp-for="IdStudent" class="form-control" readonly />
                                        <span asp-validation-for="IdStudent" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Name" class="control-label"></label>
                                        <input asp-for="Name" class="form-control" />
                                        <span asp-validation-for="Name" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="DOB" class="control-label"></label>
                                        <input asp-for="DOB" class="form-control" />
                                        <span asp-validation-for="DOB" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Faculty" class="control-label"></label>
                                        <input asp-for="Faculty" class="form-control" />
                                        <span asp-validation-for="Faculty" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Address" class="control-label"></label>
                                        <input asp-for="Address" class="form-control" />
                                        <span asp-validation-for="Address" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Class" class="control-label"></label>
                                        <input asp-for="Class" class="form-control" />
                                        <span asp-validation-for="Class" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="mobile">Mobile Number</label>
                                        <input asp-for="PhoneNumber" class="form-control" />
                                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Teacher" class="control-label"></label>
                                        <input asp-for="Teacher" class="form-control" />
                                        <span asp-validation-for="Teacher" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="email">Email</label>
                                        <input asp-for="Email" class="form-control" />
                                        <span asp-validation-for="Email" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="Idcard">Identity Card</label>
                                        <input asp-for="Idcard" class="form-control" />
                                        <span asp-validation-for="Idcard" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="Idroom">Room</label>
                                        <select asp-for="Idroom" class="form-control" asp-items="ViewBag.Idroom"></select>
                                        <span asp-validation-for="Idroom" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="PhoneParents" class="control-label"></label>
                                        <input asp-for="PhoneParents" class="form-control" />
                                        <span asp-validation-for="PhoneParents" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="AddressOfParents" class="control-label"></label>
                                        <input asp-for="AddressOfParents" class="form-control" />
                                        <span asp-validation-for="AddressOfParents" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="Idcard">Image</label>
                                        <input type="hidden" asp-for="Image" class="form-control" />
                                        <span asp-validation-for="Image" class="text-danger"></span>
                                    </div>
                                    <div class="tab-pane" id="avatar" role="tabpanel" aria-labelledby="avatar-tab">
                                        <div class="wrapper mb-5 mt-4">
                                            <span class="badge badge-warning text-white">Note : </span>
                                            <p class="d-inline ml-3 text-muted">Image size is limited to not greater than 1MB .</p>
                                        </div>
                                        <input type="file" class="dropify" data-max-file-size="1mb" name="image" />
                                    </div>
                                    <div class="form-group mt-5">
                                        <button type="submit" class="btn btn-success mr-2">Update</button>
                                        <button class="btn btn-outline-danger" asp-controller="Students" asp-action="Index">Cancel</button>
                                    </div>
                                </form>

                            </div><!-- tab content ends -->                            
                            <div class="tab-pane fade" id="security" role="tabpanel" aria-labelledby="security-tab">
                                <form action="#">
                                    <div class="form-group">
                                        <label for="change-password">Change password</label>
                                        <input type="password" class="form-control" id="change-password" placeholder="Enter you current password">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control" id="new-password" placeholder="Enter you new password">
                                    </div>
                                    <div class="form-group mt-5">
                                        <button type="submit" class="btn btn-success mr-2">Update</button>
                                        <button class="btn btn-outline-danger">Cancel</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

    @section Scripts{
        <script src="~/Scripts/Sinhvien/RegisterEvent.js"></script>       
    }
    <!-- content-wrapper ends -->

DormitoryManagement/Views/Students/Index.cshtml
@model IEnumerable<Dormitory.Entity.Data.Student>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />

<div class="row">

    <div class="col">
        <div class="row">
            <br/><br/><br/>

        </div>
        <img type="button" id="createSinhVien" src="~/images/Icon/create.png" style="width:40px; height:40px; padding-bottom: 8px; padding-left:5px">
    </div>
    <div class="col">
        <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb bg-inv">
                <li class="breadcrumb-item"><img src="~/images/Icon/home.png" style="width:20px; height:20px;" /></li>
                <li class="breadcrumb-item active" aria-current="page">Student</li>
            </ol>
        </nav>
        <div style="width:100% ; margin :auto">
            <table id="TableSinhVien" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0">
                <thead>
                    <tr>
                        <th>ID Students</th>
                        <th>Name </th>
                        <th>Class</th>
                        <th>Phone Number</th>
                        <th>Faculty</th>
                        <th>Email</th>
                        <th>ID Card</th>
                        <th>Action</th>


                    </tr>
                </thead>
            </table>
        </div>
    </div>


</div>
<div id="modal-placeholder-student" data-url="@Url.Action("Create")"></div>
@section Styles{

    <link href="~/css/myStyle.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
    <!--FANCY BOX-->
    <link rel="stylesheet" type="text/css" href="~/fancybox/jquery.fancybox.min.css" media="screen " />
}

@section Scripts{
   
    <script src="~/Scripts/Sinhvien/sinhvienDatatable.js"></script>
    <script src="~/Scripts/Sinhvien/RegisterEvent.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js" type="text/javascript"></script>
    <!-- Add mousewheel plugin (this is optional) -->
    <!---->

}