DormitoryManagement/Components/SideBarViewComponent.cs
using Dormitory.Business.Interface;
using Dormitory.Entity.Data;
using Dormitory.Ultilities.Constant;
using DormitoryManagement.Extensions;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace DormitoryManagement.Components
{
    public class SideBarViewComponent : ViewComponent
    {
        private IFunction _function;

        public SideBarViewComponent(IFunction function)
        {
            _function = function;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var roles = ((ClaimsPrincipal)User).GetSpecificClaim("Role");
            List<Function> functions;
            if (roles.Contains(CommonConstant.AdminRole))
            {
                functions = await _function.GetAll();

            }
            else
            {
                // TOTO Get by permission
                functions = new List<Function>();
            }
            return View(functions);
        }
    }
}

DormitoryManagement/Controllers/ContractsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dormitory.Entity.Data;

namespace DormitoryManagement.Controllers
{
    public class ContractsController : Controller
    {
        private readonly DormitoryContext _context;

        public ContractsController(DormitoryContext context)
        {
            _context = context;
        }

        // GET: Contracts
        public async Task<IActionResult> Index()
        {
            var dormitoryContext = _context.Contract.Include(c => c.IdemployeeNavigation).Include(c => c.IdstudentNavigation);
            return View(await dormitoryContext.ToListAsync());
        }

        // GET: Contracts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contract = await _context.Contract
                .Include(c => c.IdemployeeNavigation)
                .Include(c => c.IdstudentNavigation)
                .FirstOrDefaultAsync(m => m.KeyId == id);
            if (contract == null)
            {
                return NotFound();
            }

            return View(contract);
        }

        // GET: Contracts/Create
        public IActionResult Create()
        {
            ViewData["Idemployee"] = new SelectList(_context.Employee, "KeyId", "KeyId");
            ViewData["Idstudent"] = new SelectList(_context.Student, "KeyId", "Email");
            return View();
        }

        // POST: Contracts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Idstudent,DateStart,DateEnd,Idemployee,DateCreated,DateModified,KeyId")] Contract contract)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contract);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Idemployee"] = new SelectList(_context.Employee, "KeyId", "KeyId", contract.Idemployee);
            ViewData["Idstudent"] = new SelectList(_context.Student, "KeyId", "Email", contract.Idstudent);
            return View(contract);
        }

        // GET: Contracts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contract = await _context.Contract.FindAsync(id);
            if (contract == null)
            {
                return NotFound();
            }
            ViewData["Idemployee"] = new SelectList(_context.Employee, "KeyId", "KeyId", contract.Idemployee);
            ViewData["Idstudent"] = new SelectList(_context.Student, "KeyId", "Email", contract.Idstudent);
            return View(contract);
        }

        // POST: Contracts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Idstudent,DateStart,DateEnd,Idemployee,DateCreated,DateModified,KeyId")] Contract contract)
        {
            if (id != contract.KeyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contract);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContractExists(contract.KeyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Idemployee"] = new SelectList(_context.Employee, "KeyId", "KeyId", contract.Idemployee);
            ViewData["Idstudent"] = new SelectList(_context.Student, "KeyId", "Email", contract.Idstudent);
            return View(contract);
        }

        // GET: Contracts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contract = await _context.Contract
                .Include(c => c.IdemployeeNavigation)
                .Include(c => c.IdstudentNavigation)
                .FirstOrDefaultAsync(m => m.KeyId == id);
            if (contract == null)
            {
                return NotFound();
            }

            return View(contract);
        }

        // POST: Contracts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contract = await _context.Contract.FindAsync(id);
            _context.Contract.Remove(contract);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContractExists(int id)
        {
            return _context.Contract.Any(e => e.KeyId == id);
        }
    }
}

DormitoryManagement/Controllers/FollowsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dormitory.Entity.Data;
using Dormitory.Business.ViewModel;
using Dormitory.Business.Interface;
using Dormitory.Repositories.Repositories;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace DormitoryManagement.Controllers
{
    public class FollowsController : Controller
    {
        private readonly DormitoryContext _context;
        private readonly IFollow _follow;
        private readonly IUnitOfWork _unitOfWork;

        public FollowsController(DormitoryContext context, IFollow follow , IUnitOfWork unitOfWork)
        {
            _context = context;
            _follow = follow;
            _unitOfWork = unitOfWork;
        }

        // GET: Follows
        public async Task<IActionResult> Index()
        {
            var dormitoryContext = _context.Follow.Include(f => f.IderrorNavigation).Include(f => f.IdstudentNavigation);
            return View(await dormitoryContext.ToListAsync());
        }
        #region AJAX API
        [HttpPost]
        public IActionResult SaveEntity(FollowViewModel followVm)
        {

            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return new BadRequestObjectResult(allErrors);
            }
            else
            {
                if (followVm.KeyId == 0)
                {

                    _follow.Add(followVm);
                }
                else
                {
                    _follow.Update(followVm);
                }
                _follow.Save();
                return new OkObjectResult(followVm);
            }
        }

      
        [HttpGet]
        public IActionResult GetAll()
        {
            var model = _follow.GetAll();
            return new OkObjectResult(model);
        }
      
        [HttpGet]
        public IActionResult GetAllPaging( string keyword, int page, int pageSize)
        {
            var model = _follow.GetAllPaging(keyword, page, pageSize);
            return new OkObjectResult(model);
        }
        [HttpGet]
        public IActionResult GetById(int id)
        {
            var model = _follow.GetById(id);
            return new OkObjectResult(model);
        }
        #endregion

        // GET: Follows/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var follow = await _context.Follow
                .Include(f => f.IderrorNavigation)
                .Include(f => f.IdstudentNavigation)
                .FirstOrDefaultAsync(m => m.KeyId == id);
            if (follow == null)
            {
                return NotFound();
            }

            return View(follow);
        }

        // GET: Follows/Create
        public IActionResult Create()
        {
            ViewData["Iderror"] = new SelectList(_context.Rules, "KeyId", "KeyId");
            ViewData["Idstudent"] = new SelectList(_context.Student, "KeyId", "Email");
            return View();
        }

        // POST: Follows/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Idstudent,Iderror,Count,Date,DateCreated,DateModified,KeyId")] Follow follow)
        {
            if (ModelState.IsValid)
            {
                _context.Add(follow);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Iderror"] = new SelectList(_context.Rules, "KeyId", "KeyId", follow.Iderror);
            ViewData["Idstudent"] = new SelectList(_context.Student, "KeyId", "Email", follow.Idstudent);
            return View(follow);
        }

        // GET: Follows/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var follow = await _context.Follow.FindAsync(id);
            if (follow == null)
            {
                return NotFound();
            }
            ViewData["Iderror"] = new SelectList(_context.Rules, "KeyId", "KeyId", follow.Iderror);
            ViewData["Idstudent"] = new SelectList(_context.Student, "KeyId", "Email", follow.Idstudent);
            return View(follow);
        }

        // POST: Follows/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Idstudent,Iderror,Count,Date,DateCreated,DateModified,KeyId")] Follow follow)
        {
            if (id != follow.KeyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(follow);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FollowExists(follow.KeyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Iderror"] = new SelectList(_context.Rules, "KeyId", "KeyId", follow.Iderror);
            ViewData["Idstudent"] = new SelectList(_context.Student, "KeyId", "Email", follow.Idstudent);
            return View(follow);
        }

        // GET: Follows/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var follow = await _context.Follow
                .Include(f => f.IderrorNavigation)
                .Include(f => f.IdstudentNavigation)
                .FirstOrDefaultAsync(m => m.KeyId == id);
            if (follow == null)
            {
                return NotFound();
            }

            return View(follow);
        }

        // POST: Follows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var follow = await _context.Follow.FindAsync(id);
            _context.Follow.Remove(follow);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FollowExists(int id)
        {
            return _context.Follow.Any(e => e.KeyId == id);
        }
    }
}

DormitoryManagement/Views/Shared/Components/SideBar/Default.cshtml
@model List<Dormitory.Entity.Data.Function>

<nav class="sidebar sidebar-offcanvas" id="sidebar">
    
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" asp-controller="Home" asp-action="Index">
                <i class="mdi mdi-compass-outline menu-icon"></i>
                <span class="menu-title">Dashboard</span>
            </a>
        </li>
        @foreach (var item in Model.Where(x => string.IsNullOrEmpty(x.ParentId)))
        {
            <li class="nav-item">

                <a class="nav-link" data-toggle="collapse" href="#@item.KeyId" aria-expanded="false" aria-controls="page-layouts">
                    <i class="mdi mdi-arrow-expand-all menu-icon"></i>
                    <span class="menu-title"> @item.Name  </span>
                    <i class="menu-arrow"></i>
                </a>
                @if (Model.Any(x => x.ParentId == item.KeyId))
                {
                    <div class="collapse" id="@item.KeyId">
                        <ul class="nav flex-column sub-menu">
                            @foreach (var jitem in Model.Where(x => x.ParentId == item.KeyId))
                            {
                                @if (Model.Any(x => x.ParentId == jitem.KeyId))
                                {
                                    <li class="nav-item">
                                        <a><i class="fas @jitem.IconCss big-icon"></i> @jitem.Name <span class="fas fa-chevron-down"></span></a>
                                        <ul class="nav flex-column sub-menu">
                                            @foreach (var zjitem in Model.Where(x => x.ParentId == jitem.KeyId))
                                            {
                                                <li class="nav-item">
                                                    <a class="=nav-link" href="@zjitem.URL">
                                                        <i class="mdi mdi-compass-outline menu-icon"></i>
                                                        <span class="menu-title">@zjitem.Name</span>
                                                    </a>
                                                </li>
                                            }
                                        </ul>
                                    </li>
                                }
                                else
                                {
                                    <li><a href="@jitem.URL">@jitem.Name</a></li>
                                }

                            }

                        </ul>
                    </div>
                }

            </li>
        }
        <li class="nav-item">
            <a class="nav-link" asp-controller="Follows" asp-action="Index">
                <i class="mdi mdi-compass-outline menu-icon"></i>
                <span class="menu-title">Follow Student</span>
            </a>
        </li>
        @*<li class="nav-item">
            <a class="nav-link" asp-controller="Contracts" asp-action="Index">
                <i class="mdi mdi-compass-outline menu-icon"></i>
                <span class="menu-title">Contract Student</span>
            </a>
        </li>*@
        <li class="nav-item">
            <a class="nav-link" asp-controller="Reports" asp-action="Index">
                <i class="mdi mdi-compass-outline menu-icon"></i>
                <span class="menu-title">Report</span>
            </a>
        </li>
    </ul>

</nav>
@section Styles{ 
<link href="~/css/myStyle.css" rel="stylesheet" />
}