DormitoryManagement/Components/SideBarViewComponent.cs
using Dormitory.Business.Interface;
using Dormitory.Entity.Data;
using Dormitory.Ultilities.Constant;
using DormitoryManagement.Extensions;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace DormitoryManagement.Components
{
    public class SideBarViewComponent : ViewComponent
    {
        private IFunction _function;

        public SideBarViewComponent(IFunction function)
        {
            _function = function;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var roles = ((ClaimsPrincipal)User).GetSpecificClaim("Role");
            List<Function> functions;
            if (roles.Contains(CommonConstant.AdminRole))
            {
                functions = await _function.GetAll();

            }
            else
            {
                // TOTO Get by permission
                functions = new List<Function>();
            }
            return View(functions);
        }
    }
}

DormitoryManagement/Views/Shared/_Layout.cshtml
@using DormitoryManagement.Extensions;
<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Dormitory</title>
	<!-- plugins:css -->
	<link rel="stylesheet" href="~/node_modules/mdi/css/materialdesignicons.min.css">
	<link rel="stylesheet" href="~/node_modules/flag-icon-css/css/flag-icon.min.css">
	<link rel="stylesheet" href="~/node_modules/perfect-scrollbar/css/perfect-scrollbar.css">
	<!-- endinject -->
	<!-- plugin css for this page -->
	<link rel="stylesheet" href="~/node_modules/jvectormap/jquery-jvectormap.css" />
	<!-- End plugin css for this page -->
    <link href="~/lib/notifyjs/dist/styles/metro/notify-metro.css" rel="stylesheet" />
	<!-- inject:css -->
	<link rel="stylesheet" href="~/css/style.css">
    <link href="~/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
	<!-- endinject -->
	<link rel="shortcut icon" href="~/images/favicon.png" />
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/sweetalert2@7.33.1/dist/sweetalert2.min.css">


	@RenderSection("Styles", required: false)
</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo" href="index.html"><img src="~/images/Icon/dormitory.png" alt="logo" /></a>
                <a class="navbar-brand brand-logo-mini" href="index.html"><img src="images/logo-mini.svg" alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-stretch">
                <button class="navbar-toggler navbar-toggler align-self-center mr-2" type="button" data-toggle="minimize">
                    <i class="mdi mdi-menu"></i>
                </button>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
                            <i class="mdi mdi-bell-outline"></i>
                            <span class="count bg-success">7</span>
                        </a>
                        <div class="dropdown-menu navbar-dropdown navbar-dropdown-large preview-list" aria-labelledby="notificationDropdown">
                            <h6 class="p-3 mb-0 text-center">Notifications</h6>
                            <a class="dropdown-item preview-item">
                                <div class="preview-thumbnail">
                                    <img src="images/faces/face4.jpg" class="profile-pic">
                                </div>
                                <div class="preview-item-content">
                                    <p class="mb-0">Dany Miles <span class="text-small text-muted">commented on your photo</span></p>
                                </div>
                            </a>
                            <a class="dropdown-item preview-item">
                                <div class="preview-thumbnail">
                                    <img src="images/faces/face3.jpg" class="profile-pic">
                                </div>
                                <div class="preview-item-content">
                                    <p class="mb-0">James <span class="text-small text-muted">posted a photo on your wall</span></p>
                                </div>
                            </a>
                            <a class="dropdown-item preview-item">
                                <div class="preview-thumbnail">
                                    <img src="images/faces/face2.jpg" class="profile-pic">
                                </div>
                                <div class="preview-item-content">
                                    <p class="mb-0">Alex <span class="text-small text-muted">just mentioned you in his post</span></p>
                                </div>
                            </a>
                            <div class="dropdown-divider"></div>
                            <p class="p-3 mb-0 text-center">View all activities</p>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-toggle="dropdown">
                            <i class="mdi mdi-email-outline"></i>
                            <span class="count bg-warning">5</span>
                        </a>
                        <div class="dropdown-menu navbar-dropdown navbar-dropdown-large preview-list" aria-labelledby="messageDropdown">
                            <h6 class="p-3 mb-0 text-center">Messages</h6>
                            <a class="dropdown-item preview-item">
                                <div class="preview-item-content flex-grow">
                                    <span class="badge badge-pill badge-success">Request</span>
                                    <p class="text-small text-muted ellipsis mb-0">
                                        Suport needed for user123
                                    </p>
                                </div>
                                <p class="text-small text-muted align-self-start">4:10 PM</p>
                            </a>
                            <a class="dropdown-item preview-item">
                                <div class="preview-item-content flex-grow">
                                    <span class="badge badge-pill badge-warning">Invoices</span>
                                    <p class="text-small text-muted ellipsis mb-0">
                                        Invoice for order is mailed
                                    </p>
                                </div>
                                <p class="text-small text-muted align-self-start">4:10 PM</p>
                            </a>
                            <a class="dropdown-item preview-item">
                                <div class="preview-item-content flex-grow">
                                    <span class="badge badge-pill badge-danger">Projects</span>
                                    <p class="text-small text-muted ellipsis mb-0">
                                        New project will start tomorrow
                                    </p>
                                </div>
                                <p class="text-small text-muted align-self-start">4:10 PM</p>
                            </a>
                            <h6 class="p-3 mb-0 text-center">See all activity</h6>
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav navbar-nav-right ml-lg-auto">
                    <li class="nav-item nav-search">
                        <form class="nav-link form-inline mt-2 mt-md-0 d-none d-lg-flex">
                            <div class="input-group">
                                <input type="text"
                                       placeholder="Search">
                                <div class="input-group-append">
                                    <span class="input-group-text">
                                        <i class="mdi mdi-magnify"></i>
                                    </span>
                                </div>
                            </div>
                        </form>
                    </li>
                    <li class="nav-item dropdown d-none d-lg-flex">
                        <a class="nav-link dropdown-toggle" id="languageDropdown" href="#" data-toggle="dropdown">
                            <i class="mdi mdi-earth"></i>
                            English
                        </a>
                        <div class="dropdown-menu navbar-dropdown" aria-labelledby="languageDropdown">
                            <a class="dropdown-item" href="#">
                                French
                            </a>
                            <a class="dropdown-item" href="#">
                                Spain
                            </a>
                            <a class="dropdown-item" href="#">
                                Latin
                            </a>
                            <a class="dropdown-item" href="#">
                                Japanese
                            </a>
                        </div>
                    </li>
                    <li class="nav-item  nav-profile dropdown">
                        @await Html.PartialAsync("_LoginPartial")
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_settings-panel.html -->
            <div class="theme-setting-wrapper">
                <div id="settings-trigger"><i class="mdi mdi-settings"></i></div>
                <div id="theme-settings" class="settings-panel">
                    <i class="settings-close mdi mdi-close"></i>
                    <p class="settings-heading">SIDEBAR SKINS</p>
                    <div class="sidebar-bg-options" id="sidebar-light-theme"><div class="img-ss rounded-circle bg-light border mr-3"></div>Light</div>
                    <div class="sidebar-bg-options selected" id="sidebar-dark-theme"><div class="img-ss rounded-circle bg-dark border mr-3"></div>Dark</div>
                    <p class="settings-heading mt-2">HEADER SKINS</p>
                    <div class="color-tiles mx-0 px-4">
                        <div class="tiles primary"></div>
                        <div class="tiles success"></div>
                        <div class="tiles warning"></div>
                        <div class="tiles danger"></div>
                        <div class="tiles pink"></div>
                        <div class="tiles info"></div>
                        <div class="tiles dark"></div>
                        <div class="tiles default"></div>
                    </div>
                </div>
            </div>
            <!-- partial -->
            <!-- partial:partials/_sidebar.html -->

            @await Component.InvokeAsync("SideBar")




            <!-- partial -->
            @RenderBody()

            <!-- content-wrapper ends -->
            <!-- partial:partials/_footer.html -->
            <!-- partial -->
        </div>
        <footer class="footer">
            <div class="container-fluid clearfix">
                <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2018 <a href="#">Bootstrapdash</a>. All rights reserved.</span>
                <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
            </div>
        </footer>

        <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/node_modules/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/locale/af.js"></script>*@
    <script src="~/node_modules/perfect-scrollbar/dist/perfect-scrollbar.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/moment@2.24.0/moment.min.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <script src="~/node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <script src="~/node_modules/chart.js/dist/Chart.min.js"></script>
    <script src="~/node_modules/jvectormap/jquery-jvectormap.min.js"></script>
    <script src="~/node_modules/jvectormap/tests/assets/jquery-jvectormap-world-mill-en.js"></script>
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="~/js/off-canvas.js"></script>
    <script src="~/js/hoverable-collapse.js"></script>
    <script src="~/js/misc.js"></script>
    <script src="~/js/settings.js"></script>
    <script src="~/js/todolist.js"></script>
    <!-- endinject -->
    <script src="~/lib/mustache/mustache.js"></script>
    <!-- Custom js for this page-->
    <script src="~/js/dashboard.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
    <!-- Private zone-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twbs-pagination/1.4.2/jquery.twbsPagination.js"></script>
    <script src="~/lib/notifyjs/dist/notify.js"></script>
    <script src="~/lib/notifyjs/dist/styles/metro/notify-metro.js"></script>
    <script src="~/app/controllers/shared/dormitory.js"></script>
    <script src="~/lib/bootbox/bootbox.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <!---->
    <!-- End custom js for this page-->
    <environment include="Development">
    </environment>
    <environment exclude="Development">
        <script src="~/js/site.min.js" asp-append-version="true" defer></script>
    </environment>

    @RenderSection("Scripts", required: false)

</body>
</html>